resources:
- ../../base
namePrefix: prod-
patchesStrategicMerge:
- prod-configmap.yaml
- replica-count.yaml
configMapGenerator:
- literals:
  - TEXT1="Welcome to"
  - TEXT2="Production"
  name: rsvpconfig-prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: teamcloudyuga/rsvpapp
  newName: priyanshu92/rsvpapp
  newTag: 658e64c69b4704e5244bdd77c582cf4419cf299a
